### ISSUE TITLE
Incorrect reformatting that breaks code

### ISSUE THREAD

**Issue by VorpalBlade** [davidvarga/MBeautifier#87] opened 2020-02-27 09:31 UTC
Using Matlab R2015b I had the following code fragment:

```matlab
Q=0.7*diag([(.04)^2 (.04)^2]);
```

Using the installed shortcut the format the editor page results in:

```matlab
Q = 0.7 * diag([(.04)^2(.04)^2]);
```

These code snippets are not equivalent. The space after the first `^2` is important.

I have not changed the default configuration for MBeautifier.

I have tested with the latest release of MBeautifier (v1.3.2) as well as the latest git revision as of writing this (c77308e). Both versions exhibit the issue.

**Comment by augustjohansson** [comment] 2020-03-13 21:30
For what is worth, this also happens for
`Q = [1 (1+1)];
`
which turns into
`Q = [1(1+1)];
`
This is also with the commit https://github.com/davidvarga/MBeautifier/commit/c77308e3d58956a6493da0520e53f327f97e6eb0 .

**Comment by davidvarga** [comment] 2020-04-22 16:19
Hello guys,

I just solved this [issue](https://github.com/davidvarga/MBeautifier/issues/86) which happen to be the same problem.

I close this issue as duplicate - if the problem is not fixed, please comment on this one and I will reopen it.

Thanks!

**Comment by davidvarga** [comment] 2020-04-23 07:47
Sorry, I had to revert the commit(s), it casues something else to break - this issue is much trickier than I thought.

**Comment by davidvarga** [comment] 2020-04-23 08:46
Fixed the problem once again using a different solution.

**Closed by davidvarga** 2020-04-23 08:46 UTC
Labels: duplicate
